### ISSUE TITLE
Didn't know how to make Croatia :P 

### ISSUE THREAD

**Issue by 3Nex** [pixelastic/css-flags#10]
Ha!

**Comment by pixelastic** [comment]
Yes, all the flags that contains coats of arms (with several colors) are giving me trouble. I don't know how to do them in an efficient way. I could put a `base64` encoded image as background (but that would be cheating) or I could paint it pixel by pixel using a very long `box-shadow` (but that would be too heavy).

I haven't found an acceptable solution yet.

If you know a trick, please let me know :)
