### ISSUE TITLE
hello, your chinese flag is mistake

### ISSUE THREAD

**Issue by Go7hic** [pixelastic/css-flags#11]
Hello, the project is cool, but  i found that your chinese flg is mistake,here is the right https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E6%97%97

**Comment by pixelastic** [comment]
You are right. The small stars are slighly rotated in the original flag. Unfortunatly, I don't know how to do that in CSS (I'm using `text-shadow` to put the stars, and can't individually rotate them).

## CSS Version

![image](https://cloud.githubusercontent.com/assets/283419/20142473/27f34ada-a695-11e6-821a-f8d2e943ac9a.png)

## Wikipedia version

![image](https://cloud.githubusercontent.com/assets/283419/20142480/2d3ccf20-a695-11e6-9124-cd2d3b1ee859.png)

If you have any idea, I'm open to Pull Requests :)

**Comment by tao-guo** [comment]
![flagofchina](https://cloud.githubusercontent.com/assets/3375968/25871557/cb8b79f0-34bc-11e7-813f-b55d8f8e4f0e.png)
I have fixed this issue for chrome browser, however, it will cause firefox browser to only show yellow background due to #6

**Comment by Haroenv** [comment]
This can be closed now I think

**Comment by pixelastic** [comment]
Thanks Haroen.
