### ISSUE TITLE
Nepal Flag is missing

### ISSUE THREAD

**Issue by Wrufesh** [pixelastic/css-flags#12]
No Nepal Flag Present

**Comment by pixelastic** [comment]
It's in the favicon :)

More seriously yes, some flags are missing. I know how to do the Nepal one, I just need to find some time to do it. I'm open to Pull Requests as well ;)

**Comment by pixelastic** [comment]
![image](https://cloud.githubusercontent.com/assets/283419/20237662/a6abe710-a8d9-11e6-975f-2c478245e260.png)

Done! It was one of the more complex I had to build, though.
