### ISSUE TITLE
Spain flag missing

### ISSUE THREAD

**Issue by Benfe** [pixelastic/css-flags#15]
Hi, it seems that the spain flag is missing.

**Comment by pixelastic** [comment]
Good catch. I don't know how to do the Spanish flag, especially the coat of arm on the left of the flag. Too many colors and shapes.

![image](https://cloud.githubusercontent.com/assets/283419/20284774/e86e7154-aabe-11e6-8bb6-86e5d6855d2f.png)

If you know of a way, let me know :)

**Comment by PierrickP** [comment]
[This](https://color.typekit.com/) could be resolve many problems ;)
But only works on firefox/edge for now.

**Comment by pixelastic** [comment]
Haha, yes that would resolve *all* problems!

![image](https://cloud.githubusercontent.com/assets/283419/20519821/bb8ce580-b0a4-11e6-8375-e4e06beba4ad.png)
