### ISSUE TITLE
European Union missing flag

### ISSUE THREAD

**Issue by HLFH** [pixelastic/css-flags#16]
It seems that the EU flag is missing.

**Comment by pixelastic** [comment]
That's true. Even if I initially only planned on doing country flags, I think I can add that one as well.

For reference, here would be the [construction sheet](https://en.wikipedia.org/wiki/Flag_of_Europe#Design).

**Comment by pixelastic** [comment]
I'm going to close this issue as I don't work on this project anymore and this will cleanup my list TODO list :)

I'm open to anyone submitting a PR though.
