### ISSUE TITLE
Paraguay flag is missing.

### ISSUE THREAD

**Issue by jdromero88** [pixelastic/css-flags#24]

**Comment by pixelastic** [comment]
Thanks for the comment,

The Paraguay flag is one of the flags where I was hitting my limits. The symbol in the center is made of more than one color, so it's not something I can do with a monochrome SVG font.

for reference, here is what the Paraguay flag looks like:
![image](https://user-images.githubusercontent.com/283419/90614626-37636580-e20b-11ea-8c51-de8d7e9a866e.png)

Even if I made the star and laurel wreath out of two different characters, and the black circles with pure CSS, that would still be 3 pseudo-elements and I only have two available (`before` and `after`).

Maybe I could do something with the `:first-line` of by `:before` styled differently than the rest of the `before`, but I'm not sure that would even work.

**Comment by pixelastic** [comment]
I'm going to close this issue as I don't work on this project anymore and this will cleanup my list TODO list :)

I'm open to anyone submitting a PR though.
