### ISSUE TITLE
Firefox 47.0 flags broken

### ISSUE THREAD

**Issue by SgtOddball** [pixelastic/css-flags#6]
I've noticed there's a few flags that currently don't work in firefox correctly and i'll look at getting some fixes done when i've got some free time but at the moment they are as follows:

Algeria: - green line curves inside the cresent
Bahamas: - black triangle not rendered (just left as large black rectangle)
Brazil: - visible border lines in green area
Burundi: - lefthand triangle not rendered, 6 stars displayed not 3 with border. 
Comoros: - lefthand triangle again
Cuba: - lefthand triangle again
Djibouti: - ditto
Guyana: - multiple lefthand triangles rendered as rectangles 
Jordan: - lefthand triangle again
New Zealand: Stars duplicating and no border on them
Palestine: - lefthand triangle again
Philippines: - ditto
Qatar: No zig-zag pattern visible between two colours of the flag
Samoa: - Stars duplicating into wrong areas
Sao Tome and Principe: - lefthand triangle again
Sudan: - ditto
South Sudan: - ditto
Western Sahara: - ditto

From what I can tell, the main issue with these is the lefthand triangles and the borders around stars. 
There are a few flags that have either of those and work so will be looking into why those work and others don't (namely Timor-Leste for the lefthand triangles and Tuvalu for the stars).

**Comment by pixelastic** [comment]
Thanks for the thorough list!

I do not yet support Firefox, all my tests were made on Chrome. I tried to put in place a few unit tests using CasperCSS but the CSS properties I'm using are not handled by CasperCSS.

I would like to put a really test harness in place with Selenium, but did not found the time to do it yet. If you know how to do that, a PR would be very very welcome :)

**Comment by caseydev** [comment]
Seems great.

**Comment by caseydev** [comment]
i saw example but some css3 property still not support on firefox and ie like this one
clip path also doesn't support. we need to use svg instead of css somewhere
![image](https://cloud.githubusercontent.com/assets/4696688/17317081/9161015a-5899-11e6-9092-a1e2594fb0cf.png)

**Comment by pixelastic** [comment]
I've only made it work with Chrome so far. I'll support Firefox and other browsers once I manage to have a test suite that takes screenshots and compare them to the original.

**Comment by caseydev** [comment]
cool. I will suggest you if i find something new geeks

**Comment by ondrejsojka** [comment]
Czech Republic too, same lefthand triangle problem

**Comment by pixelastic** [comment]
I won't be able to fix any Firefox display issue until I manage to put some visual non-regression testing in place. And to be honest, the prospect of installing/managing a Selenium did not really appeal to me for now :)

**Comment by pixelastic** [comment]
I'm going to close this issue as I don't work on this project anymore and this will cleanup my list TODO list.
