### ISSUE TITLE
Name of Taiwan

### ISSUE THREAD

**Issue by ymcheung** [pixelastic/css-flags#8]
Taiwan's flag works just right.
Only the country name from ISO is outdated.

The correct names are: 'Taiwan, Republic of China' or just 'Taiwan.'

Thank you!

**Comment by pixelastic** [comment]
Thanks for the comment.

I've just fixed that:
![image](https://cloud.githubusercontent.com/assets/283419/20038859/e869ec36-a43a-11e6-8bf6-72c444670d1b.png)
