### ISSUE TITLE
Uruguay missing flag

### ISSUE THREAD

**Issue by leonelmore** [pixelastic/css-flags#9]

**Comment by pixelastic** [comment]
You're right. I didn't find any way to correctly draw the sun of the flag of Uruguay. I know how to display symbols that are of only one color (Afghanistan, China, etc), but the sun of Uruguay has a yellow background and black outlines. I still haven't found a way to do it.

I have a few ideas to try, though:
- Using a transparent icon and playing with text-shadow
- Using SVG as background and seeing if I can style differently the background and the outline
- Using two symbols and put them on top of each others

If you know how to do it, I'm open to Pull Requests ;)

**Comment by pixelastic** [comment]
I'm going to close this issue as I don't work on this project anymore and this will cleanup my list TODO list :)

I'm open to anyone submitting a PR though.
